version: '3.0'

volumes:

  nomad_server_data:
  nomad_client_data:
  docker_data:

networks:

  public-kingpin:
    external: true

services:

  nomad-server:
    image: 'kingpin-runner:1.0.0'
    container_name: 'nomad-server'
    restart: 'always'
    privileged: true
    command: ['nomad', 'agent', '-config=/nomad/config.hcl']
    networks:
      - 'public-kingpin'
    ports:
      - '4646:4646/tcp'
    volumes:
      - '/tmp:/tmp:rw'
      - './configurations/server.hcl:/nomad/config.hcl:ro'
      - 'nomad_server_data:/opt/nomad/data:rw'

  nomad-client:
    image: 'kingpin-runner:1.0.0'
    container_name: 'nomad-client'
    restart: 'always'
    privileged: true
    command: ['nomad', 'agent', '-config=/nomad/config.hcl']
    networks:
      - 'public-kingpin'
    ports:
      - '80:80/tcp'
    volumes:
      - '/tmp:/tmp:rw'
      - './configurations/client.hcl:/nomad/config.hcl:ro'
      - 'nomad_client_data:/opt/nomad/data:rw'
      - 'docker_data:/var/lib/docker:rw'


