name: traefik
region: localhost
datacenters:
  - kingpin
namespace: default
type: system

image:
  repository: traefik
  tag: v2.9.4

# trefik issue: if one env vars, then no args, all must be env vars
env:
  TRAEFIK_LOG_LEVEL: INFO
  TRAEFIK_LOG_FORMAT: json
  TRAEFIK_ACCESSLOG: 'true'
  TRAEFIK_ACCESSLOG_FORMAT: json
  TRAEFIK_PROVIDERS_NOMAD: 'true'
  TRAEFIK_PROVIDERS_NOMAD_EXPOSEDBYDEFAULT: 'false'
  TRAEFIK_PROVIDERS_NOMAD_ENDPOINT_REGION: localhost
  TRAEFIK_PROVIDERS_NOMAD_NAMESPACE: default
  TRAEFIK_PING: 'true'
  TRAEFIK_PING_ENTRYPOINT: web
  TRAEFIK_API_INSECURE: 'true'
  TRAEFIK_METRICS_PROMETHEUS: 'true'
  TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT: metrics
  TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ':80'
  TRAEFIK_ENTRYPOINTS_WEB_FORWARDEDHEADERS_INSECURE: 'true'
  TRAEFIK_ENTRYPOINTS_METRICS_ADDRESS: ':8082'

envFromSecrets:
  - name: TRAEFIK_PROVIDERS_NOMAD_ENDPOINT_ADDRESS
    source: secret/global/nomad_address

envFromServices: []

deployment:
  replicas: 1
  args: []
  resources:
    cpu: 100
    memory: 128

services:
  - name: http
    type: static
    port: 80
    tags:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.services.traefik.loadbalancer.server.scheme=http'
      - 'traefik.http.services.traefik.loadbalancer.server.port=80'
  - name: metrics
    type: to
    port: 8082
    tags: []
    