name: traefik
region: localhost
datacenters:
  - kingpin
namespace: default
type: system

image:
  repository: traefik
  tag: v2.9.4

env: []

envFromSecrets:
  - name: TRAEFIK_PROVIDERS_NOMAD_ENDPOINT_ADDRESS
    source: secret/global/nomad_address

envFromServices: []

deployment:
  replicas: 1
  args:
    - '--global.sendAnonymousUsage=false'
    - '--log.level=INFO'
    - '--log.format=json'
    - '--ping=true'
    - '--ping.entryPoint=web'
    - '--api.dashboard=true'
    - '--api.insecure=true'
    - '--entrypoints.web.address=:80'
    - '--entryPoints.web.forwardedHeaders.insecure=true'
    - '--entryPoints.metrics.address=:8082'
    - '--providers.nomad=true'
    - '--providers.nomad.exposedByDefault=false'
    - '--metrics.prometheus=true'
    - '--metrics.prometheus.entryPoint=metrics'
    - '--accesslog=true'
    - '--accesslog.format=json'
    - '--accesslog.fields.defaultmode=keep'
    - '--accesslog.fields.headers.defaultmode=keep'
  resources:
    cpu: 100
    memory: 128

services:
  - name: http
    type: static
    port: 80
    tags:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.services.traefik.loadbalancer.server.scheme=http'
      - 'traefik.http.services.traefik.loadbalancer.server.port=80'
  - name: metrics
    type: to
    port: 8082
    tags: []
    