#!/bin/bash

APP_LEVANT_VERSION="0.2.9"
APP_NOMAD_VERSION="1.4.3"
APP_MINIKUBE_VERSION="1.28.0"

echo "[INFO] clean bin directory"
rm -rf bin
mkdir bin

echo "[INFO] download levant"
curl -o bin/levant -sSL https://github.com/hashicorp/levant/releases/download/${APP_LEVANT_VERSION}/linux-amd64-levant
chmod +x bin/levant

echo "[INFO] download nomad"
curl -o nomad.zip -sSL https://releases.hashicorp.com/nomad/${APP_NOMAD_VERSION}/nomad_${APP_NOMAD_VERSION}_linux_amd64.zip
unzip nomad.zip -d ./bin
rm nomad.zip
chmod +x bin/nomad

echo "[INFO] download minikube"
curl -o bin/minikube -sSL https://github.com/kubernetes/minikube/releases/download/v${APP_MINIKUBE_VERSION}/minikube-linux-amd64
chmod +x bin/minikube
